"""
Django settings for Django_Blog project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!bvt-!&^zj-xqpdu$9xu#8*^fximunwhv@!4z1pd6+l-e381!#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',#Backstage
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig',#Application de blog
    'mdeditor',#Éditeur de markdown
    'import_export',#Importer un plug-in d'exportation
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django_Blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.views.global_params',#Variable globale personnalisée
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_Blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField' # Ou l'une des autres options selon votre choix

#DATABASES = {
#   'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'django_blog',
#        'USER': 'root',
#        'PASSWORD': 'root',
#        'HOST': 'db',
#        'PORT': '3306',
#        'OPTIONS': {'charset': 'utf8mb4'},
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = True
#日期格式
DATETIME_FORMAT = 'Y-m-d'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'blog', "static"),
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# X_FRAME_OPTIONS = 'SAMEORIGIN'

#SimpleUi后台设置
SIMPLEUI_LOGO = 'http://radiomely.com/wp-content/uploads/2018/06/radiomelylogo1.jpg' #Page de connexion et logo de fond
SIMPLEUI_ANALYSIS = False #S'il faut collecter des informations d'analyse à Simpleui
SIMPLEUI_LOADING = False #Ouvrir la couche de masque de chargement
SIMPLEUI_LOGIN_PARTICLES = True #Page de connexion Animation de particules
SIMPLEUI_STATIC_OFFLINE = True #Qu'il s'agisse de charger des ressources statiques en mode hors connexion, vous allez lire toutes les ressources par défaut lorsque cela est vrai, même si vous n'avez pas de réseautage.Convient aux projets Intranet, lorsqu'il n'est pas rempli de ceci ou de faux, par défaut, à partir d'un CDN de tiers
SIMPLEUI_HOME_INFO = False #Ouvrir les informations sur le serveur SimpleUI
SIMPLEUI_DEFAULT_THEME = 'simpleui.css' #Sujet par défaut https://simpleui.88cto.com/docs/simpleui/QUICK.html#%E9%BB%98%E8%AE%A4%E4%B8%BB%E9%A2%98
SIMPLEUI_HOME_QUICK = True #Si la page d'arrière-plan affiche l'action la plus proche
#Menu de la dent sur mesure
SIMPLEUI_CONFIG = {
    'system_keep': False,  #Supprimer le module système
    'menus': [{
        'name': 'Gestion des articles',
        'icon': 'fas fa-book-open',
        'models': [{
                'name': 'article',
                'icon': 'fas fa-book-open',
                'url': '/admin/blog/article/'
            },{
                'name': 'classification',
                'icon': 'fas fa-list',
                'url': '/admin/blog/category/'
            },{
                'name': 'étiqueter',
                'icon': 'fas fa-tags',
                'url': '/admin/blog/tag/'
            }]
    }, {
        'name': 'membre',
        'icon': 'far fa-user',
        'url': '/admin/blog/link/'
    }, {
        'name': 'Tableau d!affichage',
        'icon': 'fas fa-bullhorn',
        'url': '/admin/blog/notice/'
    },{
        'name': 'À propos de',
        'icon': 'fas fa-address-card',
        'models': [{
            'name': 'Informations de base',
            'icon': 'far fa-file',
            'url': '/admin/blog/about/'
            },{
            'name': 'Intelligence sociale',
            'icon': 'fas fa-comment-alt',
            'url': '/admin/blog/social/'
            },{
            'name': 'compétence',
            'icon': 'fas fa-drafting-compass',
            'url': '/admin/blog/skill/'
            }]
    }, {
        'name': 'Paramètres du site Web',
        'icon': 'fas fa-globe-americas',
        'url': '/admin/blog/site/'
    }, {
        'name': 'Valine Commentaire',
        'icon': 'far fa-comments',
        'url': '/admin/blog/valine/'
    }, {
        'app': 'auth',
        'name': 'Utilisateur et autorisation',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': 'utilisateur',
            'icon': 'fa fa-user',
            'url': 'auth/user/'
        },{
            'name': 'Groupes de droits',
            'icon': 'fas fa-users-cog',
            'url': 'auth/group/'
        }]
    }, {
        'name': 'Aperçu du web',
        'icon': 'fas fa-paper-plane',
        'models': [{
            'name': 'radio mega',
            'url': 'http://localhost:8000',
            'icon': 'fa fa-music'
        }]
    }]
}

# 日志记录
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format' :"[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
#             'datefmt' :"%d/%b/%Y %H:%M:%S"
#         },
#         'simple': {
#             'format': '%(levelname)s %(message)s'
#         },
#     },
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': 'mysite.log',
#             'formatter': 'verbose'
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'propagate': True,
#             'level': 'DEBUG',
#         },
#         'blog': {
#             'handlers': ['file'],
#             'level': 'DEBUG',
#         },
#     }
# }
