# Generated by Django 3.0.7 on 2021-04-10 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200430_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-add_time',), 'verbose_name': 'article', 'verbose_name_plural': 'article'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'classification', 'verbose_name_plural': 'classification'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'membre', 'verbose_name_plural': 'membre'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Paramètres du site Web', 'verbose_name_plural': 'Paramètres du site Web'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'étiqueter', 'verbose_name_plural': 'étiqueter'},
        ),
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='temps de libération'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Classification des articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité de lecture'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name="Contenu de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.URLField(default='https://i.loli.net/2020/04/23/lJLjEtbs2NFwynQ.jpg', verbose_name='Couverture de l!article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=50, verbose_name="Description d'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='Est-il recommandé?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='Annonce'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name="Le titre de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Temps de mise à jour'),
        ),
        migrations.AlterField(
            model_name='category',
            name='add_menu',
            field=models.BooleanField(default=False, verbose_name='Ajouter à la barre de navigation'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fas fa-home', max_length=30, verbose_name='Icône de navigation'),
        ),
        migrations.AlterField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Sorte'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nom de catégorie'),
        ),
        migrations.AlterField(
            model_name='link',
            name='button_word',
            field=models.CharField(default='Visiter le blog', max_length=10, verbose_name='Texte de saut'),
        ),
        migrations.AlterField(
            model_name='link',
            name='desc',
            field=models.TextField(max_length=50, verbose_name='la description'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, verbose_name='Site Internet'),
        ),
        migrations.AlterField(
            model_name='site',
            name='bg_cover',
            field=models.URLField(default='http://119.23.243.154/image/Covteam-hack.jpg', max_length=100, verbose_name='Image de fond'),
        ),
        migrations.AlterField(
            model_name='site',
            name='desc',
            field=models.CharField(max_length=50, verbose_name='Description du site Web'),
        ),
        migrations.AlterField(
            model_name='site',
            name='dynamic_slogan',
            field=models.CharField(max_length=50, verbose_name='Slogan dynamique'),
        ),
        migrations.AlterField(
            model_name='site',
            name='icp_number',
            field=models.CharField(max_length=40, verbose_name='numéro d!enregistrement'),
        ),
        migrations.AlterField(
            model_name='site',
            name='icp_url',
            field=models.URLField(default='http://example.com/', max_length=100, verbose_name='Lien d!enregistrement'),
        ),
        migrations.AlterField(
            model_name='site',
            name='keywords',
            field=models.CharField(default='Test de mots-clés', max_length=50, verbose_name='Mot-clé'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(default='radio mega', max_length=30, verbose_name='Nom de site Web'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slogan',
            field=models.CharField(max_length=50, verbose_name='Slogan de site'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name="Nom de l'étiquette"),
        ),
    ]
