# Generated by Django 3.0.7 on 2021-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210410_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='avatar',
            field=models.URLField(default='https://i.loli.net/2020/04/23/jGP8gQOYW75TSJp.png', verbose_name='Avataratar'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.URLField(default='https://jwt1399.top/favicon.png', max_length=100, verbose_name='logo du site'),
        ),
    ]
