# Generated by Django 3.0.7 on 2021-04-10 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210410_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date de l!ajout'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=400, verbose_name="Description d'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name="Le titre de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernières mise à jour'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.URLField(default='http://radiomely.com/wp-content/uploads/2018/06/radiomelylogo1.jpg', max_length=100, verbose_name='logo du site'),
        ),
    ]
