# Generated by Django 3.0.7 on 2021-04-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210410_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='https://i.loli.net/2020/04/23/lJLjEtbs2NFwynQ.jpg', upload_to='articles/', verbose_name='Couverture de l!article'),
        ),
    ]
