# Generated by Django 3.0.7 on 2021-04-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210410_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(upload_to='articles/', verbose_name='Couverture de l!article'),
        ),
    ]
