# Generated by Django 3.0.7 on 2021-04-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20210410_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='bg_cover',
            field=models.ImageField(upload_to='home-baner/', verbose_name='Image de fond'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='logo du site'),
        ),
    ]
