# Generated by Django 3.0.7 on 2021-04-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210410_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'A-propos', 'verbose_name_plural': 'A-propos'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'compétence', 'verbose_name_plural': 'compétence'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Social', 'verbose_name_plural': 'Social'},
        ),
        migrations.AlterModelOptions(
            name='valine',
            options={'verbose_name': 'examen de la valine', 'verbose_name_plural': 'examen de la valine'},
        ),
        migrations.AlterField(
            model_name='about',
            name='avatar',
            field=models.URLField(verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=50, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='about',
            name='introduction',
            field=models.TextField(verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='about',
            name='skill_title',
            field=models.CharField(default='compétence', max_length=50, verbose_name='Titre de compétence'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Contenu de l!annonce'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='icon',
            field=models.CharField(default='far fa-lightbulb', max_length=50, verbose_name='Icône d!annonce'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Titre du babillard'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=50, verbose_name='Nom du compétence'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_precent',
            field=models.CharField(default='%', max_length=50, verbose_name='pourcentage'),
        ),
        migrations.AlterField(
            model_name='social',
            name='social_desc',
            field=models.CharField(max_length=50, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='social',
            name='social_icon',
            field=models.CharField(default='fas fa-envelope', max_length=50, verbose_name='Icônes sociales'),
        ),
        migrations.AlterField(
            model_name='social',
            name='social_url',
            field=models.URLField(verbose_name='Lien social'),
        ),
    ]
