# Generated by Django 3.2.5 on 2021-07-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_emission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='button_word',
        ),
        migrations.RemoveField(
            model_name='link',
            name='title',
        ),
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
        migrations.AddField(
            model_name='link',
            name='FB_link',
            field=models.URLField(blank=True, verbose_name='Lien Facebook'),
        ),
        migrations.AddField(
            model_name='link',
            name='TW_link',
            field=models.URLField(blank=True, verbose_name='Lien Twitter'),
        ),
        migrations.AddField(
            model_name='link',
            name='WA_link',
            field=models.URLField(blank=True, verbose_name='Numero Whatsapp'),
        ),
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default=1, max_length=10, verbose_name='Nom Complet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='avatar',
            field=models.ImageField(upload_to='members-images/', verbose_name='Avatar Photo'),
        ),
    ]
