# Generated by Django 3.2.5 on 2021-07-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20210726_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='desc',
            field=models.TextField(max_length=100, verbose_name='la description'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom Complet'),
        ),
    ]
