# Generated by Django 3.2.5 on 2021-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20210726_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='about_text',
            field=models.TextField(default=1, verbose_name='Apropos du site Web'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='la description'),
        ),
    ]
