# Generated by Django 3.2.5 on 2021-07-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20210727_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_url', models.URLField(verbose_name='Lien social')),
                ('social_desc', models.CharField(max_length=50, verbose_name='introduction')),
                ('social_icon', models.CharField(default='fas fa-envelope', max_length=50, verbose_name='Icônes sociales')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Social',
            },
        ),
    ]
